from typing import List
from datetime import datetime
from ..models.event import Event

class ReportGenerator:
    """Generates professional HTML and Text reports for event summaries."""

    @staticmethod
    def generate_html_report(events: List[Event]) -> str:
        """Creates a mobile-responsive HTML email template."""
        now = datetime.now().strftime("%B %d, %Y")
        
        # Calculate impact summary
        high_impact = len([e for e in events if (e.impact_score or 0) >= 4])
        total_events = len(events)
        
        # Source breakdown
        nyrr_count = len([e for e in events if "NYRR" in e.source])
        pp_count = len([e for e in events if "Prospect Park" in e.source or "Prospect Park" in e.venue])
        w_count = len([e for e in events if "Weather" in e.source])

        rows_html = ""
        for event in events:
            rows_html += f"""
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 10px; font-weight: bold;">{event.title}</td>
                <td style="padding: 10px;">{event.start_time.strftime('%Y-%m-%d')}</td>
                <td style="padding: 10px;">{event.venue}</td>
                <td style="padding: 10px; text-align: center;">
                    {'<span style="background: #2ecc71; color: white; padding: 2px 6px; border-radius: 4px; font-size: 11px;">NEW</span>' if event.is_new else ''}
                </td>
            </tr>
            """

        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
            <div style="max-width: 600px; margin: auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
                <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
                    Weekly Event & Traffic Alert Summary
                </h2>
                <p><strong>Date:</strong> {now}</p>
                
                <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                    <div style="flex: 1; background: #f9f9f9; padding: 10px; border-radius: 4px; text-align: center;">
                        <span style="font-size: 24px; font-weight: bold; color: #3498db;">{total_events}</span><br/>
                        <span style="font-size: 12px; color: #777;">Total Events</span>
                    </div>
                    <div style="flex: 1; background: #fef9e7; padding: 10px; border-radius: 4px; text-align: center;">
                        <span style="font-size: 24px; font-weight: bold; color: #f39c12;">{high_impact}</span><br/>
                        <span style="font-size: 12px; color: #777;">High Impact</span>
                    </div>
                </div>

                <h3>Breakdown by Source</h3>
                <ul>
                    <li><strong>NYRR:</strong> {nyrr_count} races</li>
                    <li><strong>Prospect Park:</strong> {pp_count} events</li>
                    <li><strong>Weather:</strong> {w_count} alerts</li>
                </ul>

                <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                    <thead>
                        <tr style="background: #f4f4f4; text-align: left;">
                            <th style="padding: 10px;">Event</th>
                            <th style="padding: 10px;">Date</th>
                            <th style="padding: 10px;">Venue</th>
                        </tr>
                    </thead>
                    <tbody>
                        {rows_html}
                    </tbody>
                </table>
                
                <p style="font-size: 12px; color: #999; margin-top: 30px; text-align: center;">
                    Automated report generated by Event-Driven Alerts Ingestion Engine.
                </p>
            </div>
        </body>
        </html>
        """
        return html
